name: Python Voice Assistant CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Lint Python code
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # Optional: Test placeholder (you can add pytest or unittests here)
    - name: Test placeholder
      run: echo "No tests yet!"

    # Optional: Run Streamlit (note: this is for dev only, not prod deploy)
    - name: Run Streamlit (mock)
      run: |
        streamlit hello || echo "Streamlit ran successfully for testing."
